# mirror of the STEPB org's rpki objects as read from ote on 2026-08-11
#
# applying this config as-is CREATES new objects alongside the existing
# ones (arin assigns fresh roa handles). to manage the existing objects
# instead, import them first:
#
#   tofu import arin_roa.as10779 <current roa handle for as10779>
#   tofu import arin_roa.as18932 <current roa handle for as18932>
#   tofu import arin_aspa.as10779 10779
#   tofu import arin_aspa.as18932 18932
#
# roa handles rotate on every arin-side renewal or update, so look the
# current ones up via the arin_roas data source before importing.

terraform {
  required_providers {
    arin = {
      source = "registry.terraform.io/stepbrobd/arin"
    }
  }
}

# api_key comes from the ARIN_API_KEY environment variable
provider "arin" {
  org_handle = "STEPB"
  base_url   = "https://reg.ote.arin.net" # drop for production
}

resource "arin_roa" "as10779" {
  as_number = 10779
  name      = ""
  auto_link = true

  resources = [
    {
      start_address = "2602:f590::"
      cidr_length   = 36
      max_length    = 48
    },
    {
      start_address = "23.161.104.0"
      cidr_length   = 24
      max_length    = 24
    },
    {
      start_address = "192.104.136.0"
      cidr_length   = 24
      max_length    = 24
    },
  ]
}

resource "arin_roa" "as18932" {
  as_number = 18932
  name      = ""
  auto_link = true

  resources = [
    {
      start_address = "2602:f590::"
      cidr_length   = 36
      max_length    = 48
    },
    {
      start_address = "23.161.104.0"
      cidr_length   = 24
      max_length    = 24
    },
    {
      start_address = "192.104.136.0"
      cidr_length   = 24
      max_length    = 24
    },
  ]
}

resource "arin_aspa" "as10779" {
  customer_as     = 10779
  provider_as_ids = [3204, 20473, 21700, 23961, 35661, 36236]
}

resource "arin_aspa" "as18932" {
  customer_as     = 18932
  provider_as_ids = [10779]
}

# irr objects, mirrored from ote 2026-08-11
# poc links are system generated by arin from the org and cannot be
# configured; the provider exposes them as computed attributes
# member strings must match arin's stored form exactly (note the
# uppercase 2602:F590::/36 below); the provider does not canonicalize
# set member names
#
# import commands for the existing objects:
#   tofu import arin_irr_aut_num.as10779 10779
#   tofu import arin_irr_aut_num.as18932 18932
#   tofu import arin_irr_as_set.as10779_stepbrobd AS10779:AS-STEPBROBD
#   tofu import arin_irr_route_set.rs_stepbrobd RS-STEPBROBD
#   (as-sets follow the same pattern with their names)
# route objects are auto-linked to the roas above and are therefore
# managed by arin, not by arin_irr_route

resource "arin_irr_aut_num" "as10779" {
  as_number    = 10779
  as_name      = "STEPBROBD"
  descriptions = ["https://stepbrobd.com"]
  mp_imports   = ["afi any from AS10779:AS-UPSTREAM accept ANY"]
  mp_exports   = ["afi any to AS10779:AS-UPSTREAM announce AS10779:AS-TRANSIT"]
  mp_defaults  = ["to AS10779:AS-TRANSIT networks ANY"]
}

resource "arin_irr_aut_num" "as18932" {
  as_number    = 18932
  as_name      = "STEPBROBD"
  descriptions = ["https://stepbrobd.com"]
  mp_imports   = ["afi any from AS18932:AS-UPSTREAM accept ANY"]
  mp_exports   = ["afi any to AS18932:AS-UPSTREAM announce AS18932:AS-TRANSIT"]
  mp_defaults  = ["to AS18932:AS-TRANSIT networks ANY"]
}

resource "arin_irr_as_set" "as10779_stepbrobd" {
  name         = "AS10779:AS-STEPBROBD"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS10779:AS-OWN"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as10779_own" {
  name         = "AS10779:AS-OWN"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS10779", "AS18932"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as10779_transit" {
  name         = "AS10779:AS-TRANSIT"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS10779:AS-OWN", "AS209297"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as10779_upstream" {
  name         = "AS10779:AS-UPSTREAM"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS3204", "AS20473", "AS21700", "AS23961", "AS35661", "AS36236"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as18932_stepbrobd" {
  name         = "AS18932:AS-STEPBROBD"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS18932:AS-OWN"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as18932_own" {
  name         = "AS18932:AS-OWN"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS10779", "AS18932"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as18932_transit" {
  name         = "AS18932:AS-TRANSIT"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS18932:AS-OWN"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_as_set" "as18932_upstream" {
  name         = "AS18932:AS-UPSTREAM"
  descriptions = ["https://stepbrobd.com"]
  members      = ["AS10779"]
  mbrs_by_ref  = ["MNT-STEPB"]
}

resource "arin_irr_route_set" "rs_stepbrobd" {
  name         = "RS-STEPBROBD"
  descriptions = ["https://stepbrobd.com"]
  mp_members   = ["23.161.104.0/24", "44.32.189.0/24", "192.104.136.0/24", "2602:F590::/36"]
  mbrs_by_ref  = ["MNT-STEPB"]
}
